import Head from "next/head";
import Link from "next/link";
import Card from "../components/card";

export default function Home({ pokemonData, error }) {
  if (error) return <h1>Errore nel download</h1>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {pokemonData.map((pokemon) => (
        <Link href={`/pokemon/${pokemon.name}`} key={pokemon.id}>
          <Card pokemon={pokemon} />
        </Link>
      ))}
    </>
  );
}

export async function getServerSideProps() {
  const pokemonNames = ["bulbasaur", "charmander", "squirtle"];

  try {
    const pokemonDataPromises = pokemonNames.map(async (pokemon) => {
      const response = await fetch(
        `https://pokeapi.co/api/v2/pokemon/${pokemon}`
      );
      if (!response.ok) {
        throw new Error(`Failed to fetch data for ${name}`);
      }
      const { id, name, types, sprites } = await response.json();
      return { id, name, types, sprites };
    });

    const pokemonData = await Promise.all(pokemonDataPromises);
    return {
      props: { pokemonData },
    };
  } catch (error) {
    console.error("Error fetching Pokemon data:", error.message);
    return {
      props: { error: "Failed to fetch Pokemon data" },
    };
  }
}
