import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Card from "../components/card";
import { useState, useEffect } from "react";
import Modal from "@/components/modal";
import Pokedex from "@/components/Pokedex";
import Selector from "@/components/selector";

export default function Home() {
  const [selectedGen, setSelectedGen] = useState("limit=151");
  const [pokemon, setPokemon] = useState([]);

  useEffect(() => {
    fetch(`https://pokeapi.co/api/v2/pokemon/?${selectedGen}`)
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setPokemon(data.results);
      });
  }, [selectedGen]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Selector setSelectedGen={setSelectedGen} />

      <Pokedex pokemon={pokemon} />
    </>
  );
}
